export { default as ChatPlaceholderPage } from './ChatPlaceholderPage.vue'
export { default as KnowledgePlaceholderPage } from './KnowledgePlaceholderPage.vue'
export { default as PermissionDeniedPage } from './PermissionDeniedPage.vue'
export { default as SettingsPlaceholderPage } from './SettingsPlaceholderPage.vue'
export { default as TracePlaceholderPage } from './TracePlaceholderPage.vue'
